version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/postgres
    volumes:
      - .:/app

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: efekansarginn@hotmail.com # pgAdmin giriş email'i
      PGADMIN_DEFAULT_PASSWORD: admin        # pgAdmin giriş şifresi
    ports:
      - "5050:80"  # pgAdmin erişim portu
    depends_on:
      - db

volumes:
  postgres_data:
